# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  run-with-retry: kimh/run-with-retry@1.0.0
  #run-with-retry-and-clean: andreasmarkussen/run-with-retry-and-clean@0.0.1
  # run-with-retry-and-clean: andreasmarkussen/run-with-retry-and-clean@0.1.0
  # run-with-retry-and-clean: andreasmarkussen/run-with-retry-and-clean@0.1.0
  run-with-retry-and-clean: andreasmarkussen/run-with-retry-and-clean@dev:alpha2

# See https://circleci.com/docs/2.0/executor-types/
docker_image_default: &docker_image_default
    docker:
  #      - image: circleci
      - image: cimg/base:2020.01

commands:      
  run-with-retry:
    description: |
        Run command with retry. Copied from orb: kimh/run-with-retry # What will this command do? # Descriptions should be short, simple, and clear.
    parameters:
        command:
            description: Command to run
            type: string
        retry-count:
            default: 3
            description: Number of retry
            type: integer
        sleep:
            default: 5
            description: Wait duration until next retry
            type: integer
    steps:
        - run: |
            retry() {
                MAX_RETRY=<< parameters.retry-count >>
                n=0
                until [ $n -ge $MAX_RETRY ]
                do
                  "$@" && break
                  n=$[$n+1]
                  sleep << parameters.sleep >>
                done
                if [ $n -ge $MAX_RETRY ]; then
                  echo "failed: ${@}" >&2
                  exit 1
                fi
            }
            retry << parameters.command >>

  run-with-retry-and-clean:
    description: |
        Run command with retry. Copied from orb: kimh/run-with-retry # What will this command do? # Descriptions should be short, simple, and clear.
    parameters:
        command:
            description: Command to run
            type: string
        retry-count:
            default: 3
            description: Number of retry
            type: integer
        sleep:
            default: 5
            description: Wait duration until next retry
            type: integer
        clean-command:
            description: Command to run
            type: string
    steps:
        - run: |
            retry() {
                set +eo pipefail
                MAX_RETRY=<< parameters.retry-count >>
                CLEAN_UP=<< parameters.clean-command >>
                cmd="$@"
                echo "Function to call $cmd() "
                for ((n=1;n<=MAX_RETRY;n++)); do
                  echo "Attempt $n of $MAX_RETRY "
                  "$cmd"&&break
                  echo "Sleeping"
                  sleep 1
                  echo "Clean-up action '$CLEAN_UP' "
                  "$CLEAN_UP"
                done
                if [ $n -ge $MAX_RETRY ]; then
                  echo "failed: ${@}" >&2
                  exit 1
                fi
            }
            retry << parameters.command >>

jobs:
  build:
    <<: *docker_image_default
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'

  test:
    <<: *docker_image_default
    steps:
      - checkout
      - run:
          name: Create folder that will block things
          command: |
            echo "Creating the things needed to fail.. "
            mkdir -p ~/blocking-folder 
            echo JunkFile > ~/blocking-folder/data.txt
            ls -la ~/blocking-folder
            echo '#!/bin/sh' > run.sh
            echo 'echo Hello world!' >> run.sh
            echo 'find . | grep older'
            echo 'ls theFolder' >> run.sh
            echo 'mkdir -p theFolder'  >> run.sh
      - run-with-retry-and-clean:
          # name: Run 'with retry'
          command: |
            set +eo pipefail
            bash +eo pipefail run.sh
          clean-command: echo "cleaning" 
      - run-with-retry-and-clean:
          # name: Run 'with retry and clean '
          command: |
            echo "Setting pipefail"
            set +eo pipefail
            echo "I will exit fail status"
            ls -la
            sh ./mytest.sh
          clean-command: |
            echo "running clean command"
            rm -f blocking-files

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - build
      - test