version: 2.1
orbs:
  run-with-retry: kimh/run-with-retry@1.0.0
  run-with-retry-and-clean: andreasmarkussen/run-with-retry-and-clean@dev:alpha

jobs:
  test:
    run:
      name: Create folder that will block things
      command: |
        mkdir -p ~/blocking-folder 
        echo JunkFile > ~/blocking-folder/data.txt
        ls -la ~/blocking-folder
    run-with-retry-and-clean:
      name: Run commands
      command: |
        echo "I will exit fail status"
        bash my-test.sh
        exit 1
      clean-command: |
        rm -f blocking-files

      